In [ ]:
%pip install tableone

Requirement already satisfied: tableone in /usr/local/lib/python3.10/dist-packages (0.9.1)
Requirement already satisfied: jinja2>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from tableone) (3.1.4)
Requirement already satisfied: numpy>=1.19.1 in /usr/local/lib/python3.10/dist-packages (from tableone) (1.25.2)
Requirement already satisfied: openpyxl>=3.1.2 in /usr/local/lib/python3.10/dist-packages (from tableone) (3.1.5)
Requirement already satisfied: pandas>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from tableone) (2.0.3)
Requirement already satisfied: scipy>=1.10.1 in /usr/local/lib/python3.10/dist-packages (from tableone) (1.11.4)
Requirement already satisfied: statsmodels>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from tableone) (0.14.2)
Requirement already satisfied: tabulate>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from tableone) (0.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=3.1.4->tableone) (2.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl>=3.1.2->tableone) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.3->tableone) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.3->tableone) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.3->tableone) (2024.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.14.1->tableone) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.14.1->tableone) (24.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels>=0.14.1->tableone) (1.16.0)

In [ ]:
# %pip install joblib
import joblib
from google.colab import drive
drive.mount('/content/drive')
from tableone import TableOne

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import tableone
import pandas as pd

## Data loading

---

In [ ]:
microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_orange_imputed=pd.read_csv('/content/drive/MyDrive/FPS/PEANUT/analysis/data_outputs/microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_id_deleted_missing_without_imputation_with_sofa_septic_shock_simple_tree_imputed.csv',  header=0)

In [ ]:
microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_orange_imputed.head()

,interpretation,spec_type_desc,gender,admission_age,race,hospstay_seq,first_hosp_stay,first_icu_stay,myocardial_infarct,congestive_heart_failure,peripheral_vascular_disease,cerebrovascular_disease,dementia,chronic_pulmonary_disease,rheumatic_disease,peptic_ulcer_disease,mild_liver_disease,diabetes_without_cc,diabetes_with_cc,paraplegia,renal_disease,malignant_cancer,severe_liver_disease,metastatic_solid_tumor,aids,charlson_comorbidity_index,hematocrit,hemoglobin,mch,mchc,mcv,platelet,rbc,rdw,wbc,inr,pt,ptt,specimen_id,aniongap,bicarbonate,bun,calcium,chloride,creatinine,glucose,sodium,potassium,sofa_24hours,heart_rate,sbp,dbp,mbp,resp_rate,spo2,sample_origin,day_of_week_icu_admission,month_icu_admission,day_of_week_culture_request,month_culture_request,has_previous_ab,ab_group_Aminoglucósidos,ab_group_Monobactames,ab_group_Lincosamidas,ab_group_Cefalosporinas de primera generacion,ab_group_Tetraciclinas,ab_group_Carbapenémicos,ab_group_Cefalosporinas de tercera generacion,ab_group_Penicilinas,ab_group_Macrólidos,ab_group_Cefalosporinas de quinta generacion,ab_group_Oxazolidonas,ab_group_Trimetoprim + Sulfonamida,ab_group_Quinolonas,ab_group_Nitroimidazoles,ab_group_Penicilinas asociadas a inhibidores betalactamasa,ab_group_Cefalosporinas de cuarta generacion,active_principleGentamicina,active_principleAzitromicina,active_principleClaritromicina,active_principleLinezolid,active_principleCotrimoxazol,active_principleNafcilina,active_principleMeropenem,active_principleMoxifloxacino,active_principleMinociclina,active_principleClindamicina,active_principleCefepime,active_principleCefazolina,active_principleDoxiciclina,active_principleAmoxicilina-Clavulánico,active_principleAztreonam,active_principleMetronidazol,active_principleCeftriaxona,active_principleCefalexina,active_principleAmikacina,active_principleLevofloxacino,active_principleCefpodoxima,active_principleAmoxicilina,active_principleAmpicilina,active_principleCeftazidima,active_principleEritromicina,active_principleCiprofloxacino,active_principleCeftarolina,hosp_before,stay_before_same_admission,stay_before,had_R_before,had_R_before_Bloque_5,had_R_before_Bloque_4,had_R_before_Bloque_2,had_R_before_Bloque_1,had_R_before_Bloque_3,had_R_before_Bloque_6,had_R_before_no_prev_R,has_septic_shock
0,0,"FLUID,OTHER",F,64,WHITE,1,True,True,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,3,27.7,9.06059,30.0689,32.6107,91.8209,197.471,3.09526,16.2563,12.031,1.20000,14.1000,27.0,56174600.0,9.0000,20.0000,40.0000,8.00000,107.000,1.6,212.000,132.000,4.2,5.0,120.0000,175.0,68.0,103.0000,34.0000,98.0000,"FLUID,OTHER",Tuesday,April,Thursday,April,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,False,0,0,0,0,0,0,1,0
1,1,SPUTUM,F,56,WHITE,3,False,True,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2,23.6,7.90000,31.7000,33.4000,95.0000,632.000,2.49000,18.9000,25.000,1.20000,12.7000,37.0,42886500.0,25.0000,20.0000,74.0000,9.10000,85.000,4.3,85.000,125.000,5.0,13.0,90.0000,105.0,53.0,64.0000,22.0000,100.0000,SPUTUM,Wednesday,December,Friday,December,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,True,0,0,0,0,1,0,0,0
2,1,SPUTUM,M,57,WHITE,1,True,False,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,29.4,10.30000,35.2000,35.1000,100.0000,416.000,2.93000,14.4000,10.200,1.54904,24.5097,70.6,47322900.0,13.5561,24.4821,15.5853,8.33961,103.837,0.4,138.828,139.222,3.7,6.0,92.7586,132.0,74.0,87.2064,20.7317,98.3576,SPUTUM,Thursday,July,Sunday,August,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,False,0,0,0,0,0,0,1,0
3,1,MRSA SCREEN,F,81,other,1,True,False,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,8,41.0,11.90000,29.3000,29.1000,101.0000,214.868,4.08000,15.1000,9.100,1.10000,11.6000,31.7,31740600.0,12.0000,32.0000,26.0000,9.10000,103.000,2.2,126.000,142.000,5.1,5.0,54.0000,107.0,63.0,71.0000,17.0000,97.0000,MRSA SCREEN,Friday,May,Saturday,May,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,0,0,0,0,0,0,1,1
4,0,URINE,M,57,BLACK,1,True,True,1,1,1,0,0,0,0,0,1,1,0,0,1,0,0,0,0,8,46.8,14.40000,26.5000,30.8000,86.0000,149.000,5.44000,14.9000,10.100,2.80000,30.2000,39.2,10606000.0,16.0000,18.0000,21.0000,7.67014,108.000,1.1,111.000,142.000,4.1,3.0,93.1733,114.0,65.0,77.0000,20.8987,95.0000,Urine sample,Saturday,December,Sunday,December,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,1,False,0,0,0,0,0,0,1,0

### Undo dummy transformation

In [ ]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.25.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (2.0.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.1)

In [ ]:

list(microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_orange_imputed.columns)

['interpretation',
 'spec_type_desc',
 'gender',
 'admission_age',
 'race',
 'hospstay_seq',
 'first_hosp_stay',
 'first_icu_stay',
 'myocardial_infarct',
 'congestive_heart_failure',
 'peripheral_vascular_disease',
 'cerebrovascular_disease',
 'dementia',
 'chronic_pulmonary_disease',
 'rheumatic_disease',
 'peptic_ulcer_disease',
 'mild_liver_disease',
 'diabetes_without_cc',
 'diabetes_with_cc',
 'paraplegia',
 'renal_disease',
 'malignant_cancer',
 'severe_liver_disease',
 'metastatic_solid_tumor',
 'aids',
 'charlson_comorbidity_index',
 'hematocrit',
 'hemoglobin',
 'mch',
 'mchc',
 'mcv',
 'platelet',
 'rbc',
 'rdw',
 'wbc',
 'inr',
 'pt',
 'ptt',
 'specimen_id',
 'aniongap',
 'bicarbonate',
 'bun',
 'calcium',
 'chloride',
 'creatinine',
 'glucose',
 'sodium',
 'potassium',
 'sofa_24hours',
 'heart_rate',
 'sbp',
 'dbp',
 'mbp',
 'resp_rate',
 'spo2',
 'sample_origin',
 'day_of_week_icu_admission',
 'month_icu_admission',
 'day_of_week_culture_request',
 'month_culture_request',
 'has_previous_ab',
 'ab_group_Aminoglucósidos',
 'ab_group_Monobactames',
 'ab_group_Lincosamidas',
 'ab_group_Cefalosporinas de primera generacion',
 'ab_group_Tetraciclinas',
 'ab_group_Carbapenémicos',
 'ab_group_Cefalosporinas de tercera generacion',
 'ab_group_Penicilinas',
 'ab_group_Macrólidos',
 'ab_group_Cefalosporinas de quinta generacion',
 'ab_group_Oxazolidonas',
 'ab_group_Trimetoprim + Sulfonamida',
 'ab_group_Quinolonas',
 'ab_group_Nitroimidazoles',
 'ab_group_Penicilinas asociadas a inhibidores betalactamasa',
 'ab_group_Cefalosporinas de cuarta generacion',
 'active_principleGentamicina',
 'active_principleAzitromicina',
 'active_principleClaritromicina',
 'active_principleLinezolid',
 'active_principleCotrimoxazol',
 'active_principleNafcilina',
 'active_principleMeropenem',
 'active_principleMoxifloxacino',
 'active_principleMinociclina',
 'active_principleClindamicina',
 'active_principleCefepime',
 'active_principleCefazolina',
 'active_principleDoxiciclina',
 'active_principleAmoxicilina-Clavulánico',
 'active_principleAztreonam',
 'active_principleMetronidazol',
 'active_principleCeftriaxona',
 'active_principleCefalexina',
 'active_principleAmikacina',
 'active_principleLevofloxacino',
 'active_principleCefpodoxima',
 'active_principleAmoxicilina',
 'active_principleAmpicilina',
 'active_principleCeftazidima',
 'active_principleEritromicina',
 'active_principleCiprofloxacino',
 'active_principleCeftarolina',
 'hosp_before',
 'stay_before_same_admission',
 'stay_before',
 'had_R_before',
 'had_R_before_Bloque_5',
 'had_R_before_Bloque_4',
 'had_R_before_Bloque_2',
 'had_R_before_Bloque_1',
 'had_R_before_Bloque_3',
 'had_R_before_Bloque_6',
 'had_R_before_no_prev_R',
 'has_septic_shock']

In [ ]:
dummy_prefixes = ['had_R_before_','active_principle','ab_group_']
df_original = pd.DataFrame(index=microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_orange_imputed.index)
for prefix in dummy_prefixes:
    # Identificar las columnas que empiezan con el prefijo
    columns = [col for col in microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_orange_imputed.columns if col.startswith(prefix)]
    # Encontrar la columna con el valor máximo por fila y eliminar el prefijo para obtener la categoría original
    df_original[prefix.rstrip('_')] = microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_orange_imputed[columns].idxmax(axis=1).str.replace(prefix, '')

print(df_original)

     had_R_before active_principle                              ab_group
0       no_prev_R        Linezolid                          Oxazolidonas
1        Bloque_3      Gentamicina                       Aminoglucósidos
2       no_prev_R   Ciprofloxacino                            Quinolonas
3       no_prev_R      Gentamicina                       Aminoglucósidos
4       no_prev_R      Ceftriaxona  Cefalosporinas de primera generacion
...           ...              ...                                   ...
5525    no_prev_R        Nafcilina                           Penicilinas
5526    no_prev_R      Gentamicina                       Aminoglucósidos
5527    no_prev_R      Ceftriaxona  Cefalosporinas de tercera generacion
5528    no_prev_R     Azitromicina                            Macrólidos
5529    no_prev_R        Nafcilina  Cefalosporinas de primera generacion

[5530 rows x 3 columns]

In [ ]:
# Eliminar las columnas dummy del DataFrame original
columns_to_drop = [col for prefix in dummy_prefixes for col in microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_orange_imputed.columns if col.startswith(prefix)]
df_without_dummies = microbiology_icu_charlson_lab_sofa_vitals_urinedf_by_stay_orange_imputed.drop(columns=columns_to_drop)

# Unir el DataFrame con las categorías originales al DataFrame sin las columnas dummy
df_final = pd.concat([df_without_dummies, df_original], axis=1)

In [ ]:
df_final

,interpretation,spec_type_desc,gender,admission_age,race,hospstay_seq,first_hosp_stay,first_icu_stay,myocardial_infarct,congestive_heart_failure,peripheral_vascular_disease,cerebrovascular_disease,dementia,chronic_pulmonary_disease,rheumatic_disease,peptic_ulcer_disease,mild_liver_disease,diabetes_without_cc,diabetes_with_cc,paraplegia,renal_disease,malignant_cancer,severe_liver_disease,metastatic_solid_tumor,aids,charlson_comorbidity_index,hematocrit,hemoglobin,mch,mchc,mcv,platelet,rbc,rdw,wbc,inr,pt,ptt,specimen_id,aniongap,bicarbonate,bun,calcium,chloride,creatinine,glucose,sodium,potassium,sofa_24hours,heart_rate,sbp,dbp,mbp,resp_rate,spo2,sample_origin,day_of_week_icu_admission,month_icu_admission,day_of_week_culture_request,month_culture_request,has_previous_ab,hosp_before,stay_before_same_admission,stay_before,had_R_before,has_septic_shock,had_R_before,active_principle,ab_group
0,0,"FLUID,OTHER",F,64,WHITE,1,True,True,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,3,27.7000,9.06059,30.0689,32.6107,91.8209,197.471,3.09526,16.2563,12.0310,1.20000,14.1000,27.0000,56174600.0,9.0000,20.0000,40.0000,8.00000,107.000,1.60000,212.000,132.000,4.20000,5.00000,120.0000,175.000,68.0000,103.0000,34.0000,98.0000,"FLUID,OTHER",Tuesday,April,Thursday,April,1,1,0,0,False,0,no_prev_R,Linezolid,Oxazolidonas
1,1,SPUTUM,F,56,WHITE,3,False,True,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2,23.6000,7.90000,31.7000,33.4000,95.0000,632.000,2.49000,18.9000,25.0000,1.20000,12.7000,37.0000,42886500.0,25.0000,20.0000,74.0000,9.10000,85.000,4.30000,85.000,125.000,5.00000,13.00000,90.0000,105.000,53.0000,64.0000,22.0000,100.0000,SPUTUM,Wednesday,December,Friday,December,0,1,0,1,True,0,Bloque_3,Gentamicina,Aminoglucósidos
2,1,SPUTUM,M,57,WHITE,1,True,False,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,29.4000,10.30000,35.2000,35.1000,100.0000,416.000,2.93000,14.4000,10.2000,1.54904,24.5097,70.6000,47322900.0,13.5561,24.4821,15.5853,8.33961,103.837,0.40000,138.828,139.222,3.70000,6.00000,92.7586,132.000,74.0000,87.2064,20.7317,98.3576,SPUTUM,Thursday,July,Sunday,August,1,1,0,0,False,0,no_prev_R,Ciprofloxacino,Quinolonas
3,1,MRSA SCREEN,F,81,other,1,True,False,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,8,41.0000,11.90000,29.3000,29.1000,101.0000,214.868,4.08000,15.1000,9.1000,1.10000,11.6000,31.7000,31740600.0,12.0000,32.0000,26.0000,9.10000,103.000,2.20000,126.000,142.000,5.10000,5.00000,54.0000,107.000,63.0000,71.0000,17.0000,97.0000,MRSA SCREEN,Friday,May,Saturday,May,0,0,0,0,False,1,no_prev_R,Gentamicina,Aminoglucósidos
4,0,URINE,M,57,BLACK,1,True,True,1,1,1,0,0,0,0,0,1,1,0,0,1,0,0,0,0,8,46.8000,14.40000,26.5000,30.8000,86.0000,149.000,5.44000,14.9000,10.1000,2.80000,30.2000,39.2000,10606000.0,16.0000,18.0000,21.0000,7.67014,108.000,1.10000,111.000,142.000,4.10000,3.00000,93.1733,114.000,65.0000,77.0000,20.8987,95.0000,Urine sample,Saturday,December,Sunday,December,1,1,0,1,False,0,no_prev_R,Ceftriaxona,Cefalosporinas de primera generacion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5525,0,SWAB,M,78,WHITE,1,True,True,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,8,31.2000,10.20000,31.6000,32.6000,97.0000,713.000,3.22000,12.8000,20.4000,1.60000,17.7000,29.3000,40878700.0,17.0000,24.0000,52.0000,7.80000,103.000,3.00000,131.000,140.000,4.30000,10.00000,91.0000,102.000,65.0000,76.0000,22.0000,100.0000,SWAB,Thursday,June,Saturday,June,1,0,0,0,False,0,no_prev_R,Nafcilina,Penicilinas
5526,1,SPUTUM,F,87,WHITE,1,True,True,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,5,30.6612,10.00250,29.8479,32.5306,91.6903,225.734,3.37155,16.1327,12.9399,1.67431,18.3699,37.0955,47960400.0,14.2330,24.3192,35.2549,8.31048,104.434,1.38461,139.045,139.531,4.07619,4.47612,90.9630,119.182,63.2375,77.4649,21.1917,97.1869,SPUTUM,Wednesday,September,Thursday,September,0,1,0,0,False,0,no_prev_R,Gentamicina,Aminoglucósidos
5527,1,Staph aureus swab,M,28,WHITE,1,True,True,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2,28.6000,9.20000,26.6000,32.2000,83.0000,426.000,3.46000,21.8000,12.2000,1.30000,14.7000,26.2000,22255900.0,17.0000,29.0000,33.0000,8.78795,89.000,1.70000,137.986,130.000,4.60000,3.00000,107.0000,102.000,51.0000,63.0000,28.0000,97.0000,Staph aureus swab,Saturday,August,Saturday,August,1,0,0,1,False,0,no_prev_R,Ceftriaxona,Cefalosporinas de tercera generacion
5528,0,SPUTUM,M,58,WHITE,2,False,True,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2,24.0000,8.00000,34.5000,33.3000,103.0000,15.000,2.32000,16.9000,3.7000,1.30000,13.9000,26.1000,80893400.0,12.0000,26.0000,20.0000,7.60000,105.000,0.50000,161.000,139.000,4.00000,7.00000,88.0753,114.890,61.1372,76.9485,22.2612,97.5615,SPUTUM,Monday,December,Monday,December,1,1,0,1,False,1,no_prev_R,Azitromicina,Macrólidos
5529,0,BRONCHIAL WASHINGS,F,41,WHITE,1,True,True,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,2,29.2000,8.90000,26.2000,30.5000,86.0000,217.000,3.40000,14.6000,10.8000,1.10000,12.1000,33.9000,15751900.0,14.0000,26.0000,11.0000,8.20000,106.000,0.50000,106.000,146.000,3.00000,1.00000,89.3418,118.000,71.0000,85.0000,22.0825,98.3271,BRONCHIAL WASHINGS,Friday,June,Wednesday,June,1,1,0,0,False,0,no_prev_R,Nafcilina,Cefalosporinas de primera generacion

In [ ]:
# Display all columns
pd.set_option('display.max_columns', None)

# Show the first 5 rows with all columns

# Table One

In [ ]:
df_final['interpretation'] = np.where(df_final['interpretation'] == 1, 'Resistant', 'Non resistant')

In [ ]:
df_final['interpretation']

0       Non resistant
1           Resistant
2           Resistant
3           Resistant
4       Non resistant
            ...
5525    Non resistant
5526        Resistant
5527        Resistant
5528    Non resistant
5529    Non resistant
Name: interpretation, Length: 5530, dtype: object

## Select column

In [ ]:
df_final['charlson_comorbidity_index'] = df_final['charlson_comorbidity_index'].astype(int)

In [ ]:
list(df_final.select_dtypes("object"))

['interpretation',
 'spec_type_desc',
 'gender',
 'race',
 'sample_origin',
 'day_of_week_icu_admission',
 'month_icu_admission',
 'day_of_week_culture_request',
 'month_culture_request',
 'had_R_before',
 'active_principle',
 'ab_group']

In [ ]:
list(df_final.select_dtypes("number"))

['admission_age',
 'hospstay_seq',
 'myocardial_infarct',
 'congestive_heart_failure',
 'peripheral_vascular_disease',
 'cerebrovascular_disease',
 'dementia',
 'chronic_pulmonary_disease',
 'rheumatic_disease',
 'peptic_ulcer_disease',
 'mild_liver_disease',
 'diabetes_without_cc',
 'diabetes_with_cc',
 'paraplegia',
 'renal_disease',
 'malignant_cancer',
 'severe_liver_disease',
 'metastatic_solid_tumor',
 'aids',
 'charlson_comorbidity_index',
 'hematocrit',
 'hemoglobin',
 'mch',
 'mchc',
 'mcv',
 'platelet',
 'rbc',
 'rdw',
 'wbc',
 'inr',
 'pt',
 'ptt',
 'specimen_id',
 'aniongap',
 'bicarbonate',
 'bun',
 'calcium',
 'chloride',
 'creatinine',
 'glucose',
 'sodium',
 'potassium',
 'sofa_24hours',
 'heart_rate',
 'sbp',
 'dbp',
 'mbp',
 'resp_rate',
 'spo2',
 'has_previous_ab',
 'hosp_before',
 'stay_before_same_admission',
 'stay_before',
 'has_septic_shock']

In [ ]:
list(df_final.columns)

['interpretation',
 'spec_type_desc',
 'gender',
 'admission_age',
 'race',
 'hospstay_seq',
 'first_hosp_stay',
 'first_icu_stay',
 'myocardial_infarct',
 'congestive_heart_failure',
 'peripheral_vascular_disease',
 'cerebrovascular_disease',
 'dementia',
 'chronic_pulmonary_disease',
 'rheumatic_disease',
 'peptic_ulcer_disease',
 'mild_liver_disease',
 'diabetes_without_cc',
 'diabetes_with_cc',
 'paraplegia',
 'renal_disease',
 'malignant_cancer',
 'severe_liver_disease',
 'metastatic_solid_tumor',
 'aids',
 'charlson_comorbidity_index',
 'hematocrit',
 'hemoglobin',
 'mch',
 'mchc',
 'mcv',
 'platelet',
 'rbc',
 'rdw',
 'wbc',
 'inr',
 'pt',
 'ptt',
 'specimen_id',
 'aniongap',
 'bicarbonate',
 'bun',
 'calcium',
 'chloride',
 'creatinine',
 'glucose',
 'sodium',
 'potassium',
 'sofa_24hours',
 'heart_rate',
 'sbp',
 'dbp',
 'mbp',
 'resp_rate',
 'spo2',
 'sample_origin',
 'day_of_week_icu_admission',
 'month_icu_admission',
 'day_of_week_culture_request',
 'month_culture_request',
 'has_previous_ab',
 'hosp_before',
 'stay_before_same_admission',
 'stay_before',
 'had_R_before',
 'has_septic_shock',
 'had_R_before',
 'active_principle',
 'ab_group']

In [ ]:
column_name = 'had_R_before'
column_positions = np.where(np.array(df_final.columns) == column_name)[0]
column_positions
new_column_name = 'had_R_before_bin'  # Nuevo nombre para la columna en la posición 1
df_final.columns.values[64] = new_column_name

In [ ]:
df_final['had_R_before_bin'] = df_final['had_R_before_bin'].replace({True: 1, False: 0})

In [ ]:
groupby = ['interpretation']
numerical_list =[
# 'interpretation',
#  'spec_type_desc',
#  'gender',
 'admission_age',
#  'race',
 'hospstay_seq',
#  'first_hosp_stay',
#  'first_icu_stay',
#  'myocardial_infarct',
#  'congestive_heart_failure',
#  'peripheral_vascular_disease',
#  'cerebrovascular_disease',
#  'dementia',
#  'chronic_pulmonary_disease',
#  'rheumatic_disease',
#  'peptic_ulcer_disease',
#  'mild_liver_disease',
#  'diabetes_without_cc',
#  'diabetes_with_cc',
#  'paraplegia',
#  'renal_disease',
#  'malignant_cancer',
#  'severe_liver_disease',
#  'metastatic_solid_tumor',
#  'aids',
 'charlson_comorbidity_index',
 'hematocrit',
 'hemoglobin',
 'mch',
 'mchc',
 'mcv',
 'platelet',
 'rbc',
 'rdw',
 'wbc',
 'inr',
 'pt',
 'ptt',
 'specimen_id',
 'aniongap',
 'bicarbonate',
 'bun',
 'calcium',
 'chloride',
 'creatinine',
 'glucose',
 'sodium',
 'potassium',
 'sofa_24hours',
 'heart_rate',
 'sbp',
 'dbp',
 'mbp',
 'resp_rate',
 'spo2',
#  'sample_origin',
#  'day_of_week_icu_admission',
#  'month_icu_admission',
#  'day_of_week_culture_request',
#  'month_culture_request',
#  'has_previous_ab',
#  'hosp_before',
#  'stay_before_same_admission',
#  'stay_before',
#  'had_R_before',
#  'has_septic_shock',
#  'had_R_before',
#  'active_principle',
#  'ab_group'
 ]
categorical_list = ['interpretation',
 'spec_type_desc',
 'gender',
#  'admission_age',
 'race',
#  'hospstay_seq',
 'first_hosp_stay',
 'first_icu_stay',
 'myocardial_infarct',
 'congestive_heart_failure',
 'peripheral_vascular_disease',
 'cerebrovascular_disease',
 'dementia',
 'chronic_pulmonary_disease',
 'rheumatic_disease',
 'peptic_ulcer_disease',
 'mild_liver_disease',
 'diabetes_without_cc',
 'diabetes_with_cc',
 'paraplegia',
 'renal_disease',
 'malignant_cancer',
 'severe_liver_disease',
 'metastatic_solid_tumor',
 'aids',
#  'charlson_comorbidity_index',
#  'hematocrit',
#  'hemoglobin',
#  'mch',
#  'mchc',
#  'mcv',
#  'platelet',
#  'rbc',
#  'rdw',
#  'wbc',
#  'inr',
#  'pt',
#  'ptt',
#  'specimen_id',
#  'aniongap',
#  'bicarbonate',
#  'bun',
#  'calcium',
#  'chloride',
#  'creatinine',
#  'glucose',
#  'sodium',
#  'potassium',
#  'sofa_24hours',
#  'heart_rate',
#  'sbp',
#  'dbp',
#  'mbp',
#  'resp_rate',
#  'spo2',
 'sample_origin',
 'day_of_week_icu_admission',
 'month_icu_admission',
 'day_of_week_culture_request',
 'month_culture_request',
 'has_previous_ab',
 'hosp_before',
 'stay_before_same_admission',
 'stay_before',
 'had_R_before',
 'has_septic_shock',
 'had_R_before_bin',
 'active_principle',
 'ab_group'
 ]

table2 = TableOne(df_final, categorical=categorical_list, continuous=numerical_list,
                  groupby='interpretation', pval=True)

# table =TableOne(data = df_final[categorical_list + numerical_list], categorical = categorical_list, groupby= 'interpretation', pval= True)

In [ ]:
table2

                                                                                        Grouped by interpretation
                                                                                                          Missing                  Overall            Non resistant                Resistant P-Value
n                                                                                                                                     5530                     3620                     1910
interpretation, n (%)                 Non resistant                                                                            3620 (65.5)             3620 (100.0)                           <0.001
                                      Resistant                                                                                1910 (34.5)                                      1910 (100.0)
spec_type_desc, n (%)                 ABSCESS                                                                                     99 (1.8)                 61 (1.7)                 38 (2.0)  <0.001
                                      ASPIRATE                                                                                     8 (0.1)                  7 (0.2)                  1 (0.1)
                                      BILE                                                                                        57 (1.0)                 46 (1.3)                 11 (0.6)
                                      BLOOD CULTURE                                                                              444 (8.0)                209 (5.8)               235 (12.3)
                                      BRONCHIAL WASHINGS                                                                          88 (1.6)                 59 (1.6)                 29 (1.5)
                                      BRONCHOALVEOLAR LAVAGE                                                                     382 (6.9)                262 (7.2)                120 (6.3)
                                      CATHETER TIP-IV                                                                             40 (0.7)                 14 (0.4)                 26 (1.4)
                                      CSF;SPINAL FLUID                                                                             5 (0.1)                  5 (0.1)
                                      DIALYSIS FLUID                                                                               2 (0.0)                  2 (0.1)
                                      EAR                                                                                          4 (0.1)                  4 (0.1)
                                      EYE                                                                                          2 (0.0)                  1 (0.0)                  1 (0.1)
                                      FLUID RECEIVED IN BLOOD CULTURE BOTTLES                                                     15 (0.3)                  5 (0.1)                 10 (0.5)
                                      FLUID WOUND                                                                                  2 (0.0)                  1 (0.0)                  1 (0.1)
                                      FLUID,OTHER                                                                                 42 (0.8)                 27 (0.7)                 15 (0.8)
                                      FOOT CULTURE                                                                                 5 (0.1)                  4 (0.1)                  1 (0.1)
                                      FOREIGN BODY                                                                                 9 (0.2)                  5 (0.1)                  4 (0.2)
                                      Isolate                                                                                      3 (0.1)                  2 (0.1)                  1 (0.1)
                                      JOINT FLUID                                                                                  9 (0.2)                  6 (0.2)                  3 (0.2)
                                      MRSA SCREEN                                                                                189 (3.4)                 14 (0.4)                175 (9.2)
                                      Mini-BAL                                                                                   155 (2.8)                106 (2.9)                 49 (2.6)
                                      PERITONEAL FLUID                                                                            46 (0.8)                 37 (1.0)                  9 (0.5)
                                      PLEURAL FLUID                                                                               28 (0.5)                 18 (0.5)                 10 (0.5)
                                      SPUTUM                                                                                   2241 (40.5)              1433 (39.6)               808 (42.3)
                                      SWAB                                                                                       322 (5.8)                202 (5.6)                120 (6.3)
                                      Staph aureus swab                                                                           74 (1.3)                 67 (1.9)                  7 (0.4)
                                      TISSUE                                                                                      87 (1.6)                 51 (1.4)                 36 (1.9)
                                      TRACHEAL ASPIRATE                                                                            2 (0.0)                  1 (0.0)                  1 (0.1)
                                      URINE                                                                                    1140 (20.6)               945 (26.1)               195 (10.2)
                                      URINE,KIDNEY                                                                                28 (0.5)                 26 (0.7)                  2 (0.1)
                                      BLOOD CULTURE ( MYCO/F LYTIC BOTTLE)                                                         1 (0.0)                                           1 (0.1)
                                      STOOL                                                                                        1 (0.0)                                           1 (0.1)
gender, n (%)                         F                                                                                        2432 (44.0)              1646 (45.5)               786 (41.2)   0.002
                                      M                                                                                        3098 (56.0)              1974 (54.5)              1124 (58.8)
admission_age, mean (SD)                                                                                        0              64.7 (16.5)              64.3 (17.0)              65.6 (15.6)   0.005
race, n (%)                           BLACK                                                                                      535 (9.7)                348 (9.6)                187 (9.8)   0.021
                                      WHITE                                                                                    3583 (64.8)              2305 (63.7)              1278 (66.9)
                                      other                                                                                    1412 (25.5)               967 (26.7)               445 (23.3)
hospstay_seq, mean (SD)                                                                                         0                1.7 (1.9)                1.5 (1.5)                2.2 (2.3)  <0.001
first_hosp_stay, n (%)                False                                                                                    1632 (29.5)               854 (23.6)               778 (40.7)  <0.001
                                      True                                                                                     3898 (70.5)              2766 (76.4)              1132 (59.3)
first_icu_stay, n (%)                 False                                                                                      533 (9.6)                304 (8.4)               229 (12.0)  <0.001
                                      True                                                                                     4997 (90.4)              3316 (91.6)              1681 (88.0)
myocardial_infarct, n (%)             0                                                                                        4615 (83.5)              3015 (83.3)              1600 (83.8)   0.674
                                      1                                                                                         915 (16.5)               605 (16.7)               310 (16.2)
congestive_heart_failure, n (%)       0                                                                                        3771 (68.2)              2581 (71.3)              1190 (62.3)  <0.001
                                      1                                                                                        1759 (31.8)              1039 (28.7)               720 (37.7)
peripheral_vascular_disease, n (%)    0                                                                                        4838 (87.5)              3184 (88.0)              1654 (86.6)   0.159
                                      1                                                                                         692 (12.5)               436 (12.0)               256 (13.4)
cerebrovascular_disease, n (%)        0                                                                                        4426 (80.0)              2808 (77.6)              1618 (84.7)  <0.001
                                      1                                                                                        1104 (20.0)               812 (22.4)               292 (15.3)
dementia, n (%)                       0                                                                                        5307 (96.0)              3494 (96.5)              1813 (94.9)   0.005
                                      1                                                                                          223 (4.0)                126 (3.5)                 97 (5.1)
chronic_pulmonary_disease, n (%)      0                                                                                        3844 (69.5)              2608 (72.0)              1236 (64.7)  <0.001
                                      1                                                                                        1686 (30.5)              1012 (28.0)               674 (35.3)
rheumatic_disease, n (%)              0                                                                                        5328 (96.3)              3495 (96.5)              1833 (96.0)   0.310
                                      1                                                                                          202 (3.7)                125 (3.5)                 77 (4.0)
peptic_ulcer_disease, n (%)           0                                                                                        5349 (96.7)              3499 (96.7)              1850 (96.9)   0.749
                                      1                                                                                          181 (3.3)                121 (3.3)                 60 (3.1)
mild_liver_disease, n (%)             0                                                                                        4725 (85.4)              3142 (86.8)              1583 (82.9)  <0.001
                                      1                                                                                         805 (14.6)               478 (13.2)               327 (17.1)
diabetes_without_cc, n (%)            0                                                                                        4087 (73.9)              2718 (75.1)              1369 (71.7)   0.007
                                      1                                                                                        1443 (26.1)               902 (24.9)               541 (28.3)
diabetes_with_cc, n (%)               0                                                                                        4953 (89.6)              3280 (90.6)              1673 (87.6)   0.001
                                      1                                                                                         577 (10.4)                340 (9.4)               237 (12.4)
paraplegia, n (%)                     0                                                                                        5007 (90.5)              3235 (89.4)              1772 (92.8)  <0.001
                                      1                                                                                          523 (9.5)               385 (10.6)                138 (7.2)
renal_disease, n (%)                  0                                                                                        4221 (76.3)              2860 (79.0)              1361 (71.3)  <0.001
                                      1                                                                                        1309 (23.7)               760 (21.0)               549 (28.7)
malignant_cancer, n (%)               0                                                                                        4885 (88.3)              3224 (89.1)              1661 (87.0)   0.023
                                      1                                                                                         645 (11.7)               396 (10.9)               249 (13.0)
severe_liver_disease, n (%)           0                                                                                        5167 (93.4)              3439 (95.0)              1728 (90.5)  <0.001
                                      1                                                                                          363 (6.6)                181 (5.0)                182 (9.5)
metastatic_solid_tumor, n (%)         0                                                                                        5265 (95.2)              3442 (95.1)              1823 (95.4)   0.594
                                      1                                                                                          265 (4.8)                178 (4.9)                 87 (4.6)
aids, n (%)                           0                                                                                        5483 (99.2)              3593 (99.3)              1890 (99.0)   0.314
                                      1                                                                                           47 (0.8)                 27 (0.7)                 20 (1.0)
charlson_comorbidity_index, mean (SD)                                                                           0                5.1 (2.9)                4.9 (2.9)                5.5 (2.9)  <0.001
hematocrit, mean (SD)                                                                                           0               30.7 (5.2)               31.2 (5.4)               29.7 (4.8)  <0.001
hemoglobin, mean (SD)                                                                                           0               10.0 (1.8)               10.2 (1.8)                9.6 (1.6)  <0.001
mch, mean (SD)                                                                                                  0               29.8 (2.4)               29.9 (2.4)               29.7 (2.3)   0.014
mchc, mean (SD)                                                                                                 0               32.5 (1.6)               32.6 (1.6)               32.3 (1.6)  <0.001
mcv, mean (SD)                                                                                                  0               91.7 (6.5)               91.6 (6.5)               92.0 (6.4)   0.023
platelet, mean (SD)                                                                                             0            222.8 (124.2)            219.9 (117.0)            228.2 (136.8)   0.025
rbc, mean (SD)                                                                                                  0                3.4 (0.6)                3.4 (0.6)                3.2 (0.6)  <0.001
rdw, mean (SD)                                                                                                  0               15.9 (2.3)               15.6 (2.2)               16.5 (2.3)  <0.001
wbc, mean (SD)                                                                                                  0               13.1 (9.3)               13.0 (9.9)               13.3 (8.1)   0.197
inr, mean (SD)                                                                                                  0                1.5 (0.7)                1.5 (0.7)                1.6 (0.7)  <0.001
pt, mean (SD)                                                                                                   0               16.9 (7.3)               16.4 (7.2)               17.7 (7.5)  <0.001
ptt, mean (SD)                                                                                                  0              37.6 (17.5)              36.8 (17.3)              39.0 (17.6)  <0.001
specimen_id, mean (SD)                                                                                          0  50168141.1 (27354024.0)  50131468.2 (27503394.2)  50237646.8 (27075694.6)   0.890
aniongap, mean (SD)                                                                                             0               14.5 (3.8)               14.5 (3.7)               14.6 (4.0)   0.390
bicarbonate, mean (SD)                                                                                          0               24.1 (4.9)               24.0 (4.7)               24.3 (5.2)   0.105
bun, mean (SD)                                                                                                  0              32.7 (23.6)              31.0 (22.6)              35.7 (25.1)  <0.001
calcium, mean (SD)                                                                                              0                8.3 (0.7)                8.3 (0.7)                8.3 (0.7)   0.172
chloride, mean (SD)                                                                                             0              104.1 (6.7)              104.2 (6.7)              103.7 (6.7)   0.012
creatinine, mean (SD)                                                                                           0                1.5 (1.4)                1.5 (1.4)                1.7 (1.5)  <0.001
glucose, mean (SD)                                                                                              0             141.0 (59.1)             141.5 (57.5)             140.0 (61.9)   0.380
sodium, mean (SD)                                                                                               0              139.5 (5.6)              139.6 (5.6)              139.4 (5.6)   0.095
potassium, mean (SD)                                                                                            0                4.1 (0.6)                4.1 (0.6)                4.1 (0.6)   0.014

In [ ]:
# Save table to HTML
fn3 = '/content/drive/MyDrive/FPS/PEANUT/analysis/20240705_tableone_sime_tree_imputed.html'
table2.to_html(fn3)

In [ ]:
# table.to_excel("/content/drive/MyDrive/FPS/PEANUT/analysis/tableone_orange_imputed.xlsx", encoding='utf-8')